name: Rails 指南
author: Andor Chen
author_url: http://about.ac
baseurl: http://docs-china.com/rails
home: http://docs-china.com
repo: rails
buy_url: https://leanpub.com/rails-guides-cn
license: <a href="http://creativecommons.org/licenses/by-sa/3.0/deed.zh" title="CC BY-SA 3.0">CC BY-SA 3.0</a>

pages: _docs
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'README.md']
keep_files: ['.git', 'images', 'scripts', '.nojekyll', 'README.md']
markdown_ext: foolish
kramdown:
  auto_ids: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
